### ISSUE TITLE
Is my worship open source?

### ISSUE THREAD

**Issue by arnoldfungai** [musicmunky/myworship#1]
@musicmunky, Please advise if `myworship `is open sourced. I would like to clone, and implement here in Harare, Zimbabwe.

**Comment by musicmunky** [comment]
yes, this project is completely open source - feel free to clone or fork and use however you'd like, as long as you don't sell it.

**Comment by arnoldfungai** [comment]
Thanks @musicmunky. I am an absolute novice in regards to Rails! I am getting in a muddle trying to install the app on local machine. 

I have performed a `bundle install` successfully.

But, the `rake db:setup` is not successful as there is no `database.yml` file in `/config`.

Could you be kind to advise the steps I need to follow to get my worship up and running.

Eventually I would like to host on **Heroku** if possible.

Many thanks

**Comment by musicmunky** [comment]
Hey, yeah you'll need to create your own database.yml file in the config directory.  In general when you put a rails project on github you shouldn't commit your database.yml file (or you should commit it with dummy information) because many times it will contain the login information about your database.  
  
Here's what a basic database.yml file looks like:  
  

`default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <database_username>
  password: <database_password>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: myworship_development

test:
  <<: *default
  database: myworship_test

production:
  <<: *default
  database: myworship_production
  username: myworship
  password: <%= ENV['MYWORSHIP_DATABASE_PASSWORD'] %>`  
  
If that doesn't help try googling around for examples of the file.  Good luck bud
